"""Core API: use case factories, auth dependencies, and core routes."""

from core.api.core_routes import router as core_router
from core.api.dependencies import (
    get_regions_use_case,
    get_provinces_by_region_use_case,
    get_municipalities_by_province_use_case,
    get_sub_municipal_areas_by_municipality_use_case,
    get_green_areas_use_case,
    get_green_assets_use_case,
    get_regions_uc,
    get_provinces_uc,
    get_municipalities_uc,
    get_sub_municipal_areas_uc,
    get_green_areas_uc,
    get_green_assets_uc,
    CurrentUser,
    OptionalCurrentUser,
    Authorized,
    get_current_user,
    get_authorization,
    pre_authorize,
)

__all__ = [
    "core_router",
    "get_regions_use_case",
    "get_provinces_by_region_use_case",
    "get_municipalities_by_province_use_case",
    "get_sub_municipal_areas_by_municipality_use_case",
    "get_green_areas_use_case",
    "get_green_assets_use_case",
    "get_regions_uc",
    "get_provinces_uc",
    "get_municipalities_uc",
    "get_sub_municipal_areas_uc",
    "get_green_areas_uc",
    "get_green_assets_uc",
    "CurrentUser",
    "OptionalCurrentUser",
    "Authorized",
    "get_current_user",
    "get_authorization",
    "pre_authorize",
]
