-- =============================================================================
-- Seed: secondary_types + translations
-- =============================================================================
-- From docs/database/area/obt/types/secondary_types.md. primary_type_id from CODICE TP.
-- Run after 01b-2-seed-primary-types.sql.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- SECONDARY_TYPES (1=Vegetazione 01-03, 2=Arredo 04-24,28-39,42, 3=Fruizione 25-27,99, 4=Fattori 40,41,43,50)
-- -----------------------------------------------------------------------------
INSERT INTO public.secondary_types (id, ts_code, primary_type_id, description_code)
VALUES
  (1, '01', 1, 'TS_DESC_01'),
  (2, '02', 1, 'TS_DESC_02'),
  (3, '03', 1, 'TS_DESC_03'),
  (4, '04', 2, 'TS_DESC_04'),
  (5, '05', 2, 'TS_DESC_05'),
  (6, '06', 2, 'TS_DESC_06'),
  (7, '07', 2, 'TS_DESC_07'),
  (8, '08', 2, 'TS_DESC_08'),
  (9, '09', 2, 'TS_DESC_09'),
  (10, '10', 2, 'TS_DESC_10'),
  (11, '11', 2, 'TS_DESC_11'),
  (12, '12', 2, 'TS_DESC_12'),
  (13, '13', 2, 'TS_DESC_13'),
  (14, '14', 2, 'TS_DESC_14'),
  (15, '15', 2, 'TS_DESC_15'),
  (16, '16', 2, 'TS_DESC_16'),
  (17, '17', 2, 'TS_DESC_17'),
  (18, '18', 2, 'TS_DESC_18'),
  (19, '19', 2, 'TS_DESC_19'),
  (20, '20', 2, 'TS_DESC_20'),
  (21, '21', 2, 'TS_DESC_21'),
  (22, '22', 2, 'TS_DESC_22'),
  (23, '23', 2, 'TS_DESC_23'),
  (24, '24', 2, 'TS_DESC_24'),
  (25, '25', 3, 'TS_DESC_25'),
  (26, '26', 3, 'TS_DESC_26'),
  (27, '27', 3, 'TS_DESC_27'),
  (28, '28', 2, 'TS_DESC_28'),
  (29, '29', 2, 'TS_DESC_29'),
  (30, '30', 2, 'TS_DESC_30'),
  (31, '31', 2, 'TS_DESC_31'),
  (32, '32', 2, 'TS_DESC_32'),
  (33, '33', 2, 'TS_DESC_33'),
  (34, '34', 2, 'TS_DESC_34'),
  (35, '35', 2, 'TS_DESC_35'),
  (36, '36', 2, 'TS_DESC_36'),
  (37, '37', 2, 'TS_DESC_37'),
  (38, '38', 2, 'TS_DESC_38'),
  (39, '39', 2, 'TS_DESC_39'),
  (40, '40', 4, 'TS_DESC_40'),
  (41, '41', 4, 'TS_DESC_41'),
  (42, '42', 2, 'TS_DESC_42'),
  (43, '43', 4, 'TS_DESC_43'),
  (44, '50', 4, 'TS_DESC_50'),
  (45, '99', 3, 'TS_DESC_99')
ON CONFLICT (id) DO UPDATE SET
  ts_code = EXCLUDED.ts_code,
  primary_type_id = EXCLUDED.primary_type_id,
  description_code = EXCLUDED.description_code;

-- -----------------------------------------------------------------------------
-- TRANSLATIONS for secondary_types
-- -----------------------------------------------------------------------------
INSERT INTO public.translations (entity_type, entity_name, key, column_name, lang, translation)
VALUES
  ('TABLE', 'secondary_types', 'TS_DESC_01', 'description_code', 'it', 'Prato'),
  ('TABLE', 'secondary_types', 'TS_DESC_01', 'description_code', 'en', 'Lawn'),
  ('TABLE', 'secondary_types', 'TS_DESC_02', 'description_code', 'it', 'Aiuola'),
  ('TABLE', 'secondary_types', 'TS_DESC_02', 'description_code', 'en', 'Flower bed'),
  ('TABLE', 'secondary_types', 'TS_DESC_03', 'description_code', 'it', 'Pianta'),
  ('TABLE', 'secondary_types', 'TS_DESC_03', 'description_code', 'en', 'Plant'),
  ('TABLE', 'secondary_types', 'TS_DESC_04', 'description_code', 'it', 'Specchio d''acqua'),
  ('TABLE', 'secondary_types', 'TS_DESC_04', 'description_code', 'en', 'Water body'),
  ('TABLE', 'secondary_types', 'TS_DESC_05', 'description_code', 'it', 'Area pavimentata'),
  ('TABLE', 'secondary_types', 'TS_DESC_05', 'description_code', 'en', 'Paved area'),
  ('TABLE', 'secondary_types', 'TS_DESC_06', 'description_code', 'it', 'Impianti sportivi - pallavolo/basket'),
  ('TABLE', 'secondary_types', 'TS_DESC_06', 'description_code', 'en', 'Sports facilities - volleyball/basketball'),
  ('TABLE', 'secondary_types', 'TS_DESC_07', 'description_code', 'it', 'Impianti sportivi - campo bocce'),
  ('TABLE', 'secondary_types', 'TS_DESC_07', 'description_code', 'en', 'Sports facilities - bowls court'),
  ('TABLE', 'secondary_types', 'TS_DESC_08', 'description_code', 'it', 'Impianti sportivi - pista schettinaggio'),
  ('TABLE', 'secondary_types', 'TS_DESC_08', 'description_code', 'en', 'Sports facilities - skating rink'),
  ('TABLE', 'secondary_types', 'TS_DESC_09', 'description_code', 'it', 'Impianti sportivi - calcio'),
  ('TABLE', 'secondary_types', 'TS_DESC_09', 'description_code', 'en', 'Sports facilities - football'),
  ('TABLE', 'secondary_types', 'TS_DESC_10', 'description_code', 'it', 'Impianti sportivi - calcetto'),
  ('TABLE', 'secondary_types', 'TS_DESC_10', 'description_code', 'en', 'Sports facilities - five-a-side football'),
  ('TABLE', 'secondary_types', 'TS_DESC_11', 'description_code', 'it', 'Impianti sportivi - altro'),
  ('TABLE', 'secondary_types', 'TS_DESC_11', 'description_code', 'en', 'Sports facilities - other'),
  ('TABLE', 'secondary_types', 'TS_DESC_12', 'description_code', 'it', 'Edificio'),
  ('TABLE', 'secondary_types', 'TS_DESC_12', 'description_code', 'en', 'Building'),
  ('TABLE', 'secondary_types', 'TS_DESC_13', 'description_code', 'it', 'Manufatto edilizio architettonico'),
  ('TABLE', 'secondary_types', 'TS_DESC_13', 'description_code', 'en', 'Architectural building structure'),
  ('TABLE', 'secondary_types', 'TS_DESC_14', 'description_code', 'it', 'Manufatto arredo urbano'),
  ('TABLE', 'secondary_types', 'TS_DESC_14', 'description_code', 'en', 'Urban furniture structure'),
  ('TABLE', 'secondary_types', 'TS_DESC_15', 'description_code', 'it', 'Muro'),
  ('TABLE', 'secondary_types', 'TS_DESC_15', 'description_code', 'en', 'Wall'),
  ('TABLE', 'secondary_types', 'TS_DESC_16', 'description_code', 'it', 'Cordolo'),
  ('TABLE', 'secondary_types', 'TS_DESC_16', 'description_code', 'en', 'Kerb'),
  ('TABLE', 'secondary_types', 'TS_DESC_17', 'description_code', 'it', 'Recinzione'),
  ('TABLE', 'secondary_types', 'TS_DESC_17', 'description_code', 'en', 'Fence'),
  ('TABLE', 'secondary_types', 'TS_DESC_18', 'description_code', 'it', 'Cancello'),
  ('TABLE', 'secondary_types', 'TS_DESC_18', 'description_code', 'en', 'Gate'),
  ('TABLE', 'secondary_types', 'TS_DESC_19', 'description_code', 'it', 'Panchina'),
  ('TABLE', 'secondary_types', 'TS_DESC_19', 'description_code', 'en', 'Bench'),
  ('TABLE', 'secondary_types', 'TS_DESC_20', 'description_code', 'it', 'Canalina scolo acque'),
  ('TABLE', 'secondary_types', 'TS_DESC_20', 'description_code', 'en', 'Water drainage channel'),
  ('TABLE', 'secondary_types', 'TS_DESC_21', 'description_code', 'it', 'Pozzetto'),
  ('TABLE', 'secondary_types', 'TS_DESC_21', 'description_code', 'en', 'Manhole / catch pit'),
  ('TABLE', 'secondary_types', 'TS_DESC_22', 'description_code', 'it', 'Fontanella'),
  ('TABLE', 'secondary_types', 'TS_DESC_22', 'description_code', 'en', 'Drinking fountain'),
  ('TABLE', 'secondary_types', 'TS_DESC_23', 'description_code', 'it', 'Idrante'),
  ('TABLE', 'secondary_types', 'TS_DESC_23', 'description_code', 'en', 'Hydrant'),
  ('TABLE', 'secondary_types', 'TS_DESC_24', 'description_code', 'it', 'Cestino'),
  ('TABLE', 'secondary_types', 'TS_DESC_24', 'description_code', 'en', 'Waste bin'),
  ('TABLE', 'secondary_types', 'TS_DESC_25', 'description_code', 'it', 'Area convenzionata'),
  ('TABLE', 'secondary_types', 'TS_DESC_25', 'description_code', 'en', 'Management area'),
  ('TABLE', 'secondary_types', 'TS_DESC_26', 'description_code', 'it', 'Area assegnazione temporanea'),
  ('TABLE', 'secondary_types', 'TS_DESC_26', 'description_code', 'en', 'Temporary assignment area'),
  ('TABLE', 'secondary_types', 'TS_DESC_27', 'description_code', 'it', 'Area funzionale'),
  ('TABLE', 'secondary_types', 'TS_DESC_27', 'description_code', 'en', 'Functional area'),
  ('TABLE', 'secondary_types', 'TS_DESC_28', 'description_code', 'it', 'Impianti sportivi - pista ciclabile'),
  ('TABLE', 'secondary_types', 'TS_DESC_28', 'description_code', 'en', 'Sports facilities - cycle path'),
  ('TABLE', 'secondary_types', 'TS_DESC_29', 'description_code', 'it', 'Impianti sportivi - piattaforma skateboard'),
  ('TABLE', 'secondary_types', 'TS_DESC_29', 'description_code', 'en', 'Sports facilities - skateboard platform'),
  ('TABLE', 'secondary_types', 'TS_DESC_30', 'description_code', 'it', 'Accesso'),
  ('TABLE', 'secondary_types', 'TS_DESC_30', 'description_code', 'en', 'Access'),
  ('TABLE', 'secondary_types', 'TS_DESC_31', 'description_code', 'it', 'Scala/Rampa'),
  ('TABLE', 'secondary_types', 'TS_DESC_31', 'description_code', 'en', 'Stairs / ramp'),
  ('TABLE', 'secondary_types', 'TS_DESC_32', 'description_code', 'it', 'Elemento del sistema di irrigazione'),
  ('TABLE', 'secondary_types', 'TS_DESC_32', 'description_code', 'en', 'Irrigation system element'),
  ('TABLE', 'secondary_types', 'TS_DESC_33', 'description_code', 'it', 'Impianti sportivi - rugby'),
  ('TABLE', 'secondary_types', 'TS_DESC_33', 'description_code', 'en', 'Sports facilities - rugby'),
  ('TABLE', 'secondary_types', 'TS_DESC_34', 'description_code', 'it', 'Impianti sportivi - tennis'),
  ('TABLE', 'secondary_types', 'TS_DESC_34', 'description_code', 'en', 'Sports facilities - tennis'),
  ('TABLE', 'secondary_types', 'TS_DESC_35', 'description_code', 'it', 'Impianti sportivi - softball'),
  ('TABLE', 'secondary_types', 'TS_DESC_35', 'description_code', 'en', 'Sports facilities - softball'),
  ('TABLE', 'secondary_types', 'TS_DESC_36', 'description_code', 'it', 'Impianti sportivi - baseball'),
  ('TABLE', 'secondary_types', 'TS_DESC_36', 'description_code', 'en', 'Sports facilities - baseball'),
  ('TABLE', 'secondary_types', 'TS_DESC_37', 'description_code', 'it', 'Impianti sportivi - atletica'),
  ('TABLE', 'secondary_types', 'TS_DESC_37', 'description_code', 'en', 'Sports facilities - athletics'),
  ('TABLE', 'secondary_types', 'TS_DESC_38', 'description_code', 'it', 'Impianti sportivi – mini calcio'),
  ('TABLE', 'secondary_types', 'TS_DESC_38', 'description_code', 'en', 'Sports facilities - mini football'),
  ('TABLE', 'secondary_types', 'TS_DESC_39', 'description_code', 'it', 'Impianti sportivi – mini basket'),
  ('TABLE', 'secondary_types', 'TS_DESC_39', 'description_code', 'en', 'Sports facilities - mini basketball'),
  ('TABLE', 'secondary_types', 'TS_DESC_40', 'description_code', 'it', 'Area soggetta a malattie'),
  ('TABLE', 'secondary_types', 'TS_DESC_40', 'description_code', 'en', 'Disease-prone area'),
  ('TABLE', 'secondary_types', 'TS_DESC_41', 'description_code', 'it', 'Infrastrutture'),
  ('TABLE', 'secondary_types', 'TS_DESC_41', 'description_code', 'en', 'Infrastructure'),
  ('TABLE', 'secondary_types', 'TS_DESC_42', 'description_code', 'it', 'Pavimentazioni antitrauma'),
  ('TABLE', 'secondary_types', 'TS_DESC_42', 'description_code', 'en', 'Impact-absorbing surfacing'),
  ('TABLE', 'secondary_types', 'TS_DESC_43', 'description_code', 'it', 'Analisi specialistiche'),
  ('TABLE', 'secondary_types', 'TS_DESC_43', 'description_code', 'en', 'Specialist analysis'),
  ('TABLE', 'secondary_types', 'TS_DESC_50', 'description_code', 'it', 'Eventi accidentali'),
  ('TABLE', 'secondary_types', 'TS_DESC_50', 'description_code', 'en', 'Accidental events'),
  ('TABLE', 'secondary_types', 'TS_DESC_99', 'description_code', 'it', 'Informazione geodetica'),
  ('TABLE', 'secondary_types', 'TS_DESC_99', 'description_code', 'en', 'Geodetic information')
ON CONFLICT (entity_type, entity_name, key, lang, column_name) DO UPDATE SET
  translation = EXCLUDED.translation;
